using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; //autogenerated
using System.Linq;
using System.Web;

namespace PoolsExample.Models
{
    public class Bookings
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Book_Id { get; set; }
        public string Cust_Name { get; set; }
        public int No_Visitors { get; set; }
        public int Pool_Id { get; set; }
        public virtual Pools Pools { get; set; }
        public int Time_id { get; set; }
        public virtual Timeclass Timeclass { get; set; }
        public double Costs { get; set; }

        //2
        public double Pullprice()
        {
            PoolsDbContext db = new PoolsDbContext();
            var pri = (from r in db.pool
                       where r.Pool_Id == Pool_Id
                       select r.Cost).FirstOrDefault();
            return pri;
        }

        //3
        public double CalcBasicCost()
        {
            return Pullprice() * No_Visitors;
        }

        //4
        public double Pullrate()
        {
            PoolsDbContext db = new PoolsDbContext();
            var disc = (from d in db.time
                        where d.Time_id == Time_id
                        select d.Day_Time_Disc_Rate).FirstOrDefault();
            return disc;
        }

        public double DiscAmount()
        {
            return Pullrate() * CalcBasicCost();
        }

        public double CalcTotal()
        {
            return (CalcBasicCost() - DiscAmount());
        }
    }

}